### ISSUE TITLE
setTemplateSeparators not working

### ISSUE THREAD

**Issue by kouts** [foo123/Contemplate#5]
Looking for a way to set seperators globally I noticed that setTemplateSeparators function was not working. I created a pull request for that, but maybe you have a better way of fixing it.

**Comment by foo123** [comment]
Yes, this feature was there initally, separators were global, but configurable. This has the problem of embedding templates within templates, since then the same separators will break the inside templates. For example think of a webpage (.html.tpl) which itself is a template (for example uses the <%, %> separators), but inside this page other templates are defined (for example to be used by javascript) Then there is conflict of the separatotrs ane everything breaks. So the solution to this problem was taken for each temnplate to define its own separators (in the first line). This solves two problems actually The one already mentioned and the other is the fact that in this way Contemplate templates can be quite flexible to stand as te\mplates for a wide variety of text formats, e;g html, xml, javascript, sql etc..

**Comment by foo123** [comment]
Plus if one needs to mix templates and embed in one another, without the option of each template defining (and taking responsibility of) its own separators (as it knows its own content). One would have to keep track of the various separartor confi\licts manualy in the code and this can easily become a spaggeti nightmare.

**Comment by kouts** [comment]
Considering the fact that other template engines do not even allow one to change the seperators, allowing this in Contemplate is a big plus. So if I understand correctly if I want to have subtemplates, the subtemplates must have different seperators from the master template? Is this the reason why we must define seperators in each template individually?

**Comment by foo123** [comment]
Well let me give some of my use cases. For example i had a Joomla application/component where i used Contemplate for all templates (server-side .php + client-side .js) But you see sometimes the server-side template has to include (or is better to pre-include) the client-side templates (which are supposed to be rendered on the browser and NOT the server). So in embeding the client-side templates inside the server-side templates will break the templates since they will be parsed at server-side (due to having same separators). To solve this problem one notices the fact that each template should be responsible to **define iits own separators independantly of other templates, since only the template  itself knows its own content (and use-intent)**. So this was found to be the best and modular solution. Note however that one can bypass this by using custom separators option when calling the template as:

``` javascript
Contemplate.tpl("tplID", data, {separators: "<% %>"});
```

And this will override any separators defined inside the template itself (this feature is also used in the said application, when compiling a pre-parsed template, so no separators are there)

**Comment by kouts** [comment]
Thank you for the explanation, now I understand the need to do this. Since I plan to use Contemplate only on client side, I never thought of such a conflict happening. I really like the approach "one template syntax" for both PHP and JS in the same app though.

**Comment by foo123** [comment]
Welcome, this is the whole point in creating Contemplate in the first place, a **uniform** (or some say **isomorphic**) template functionality at various levels of web application. Plus flexibility to be used for various text formats, i.e html,xml,sql,javascript,php whatever and not only for html/xml templating.

Presumably one can use Contemplate to even generate source code
