### ISSUE TITLE
Chrome App Extension

### ISSUE THREAD

**Issue by sawyerlin** [foo123/Contemplate#6]
Hi, I tried your library in Chrome App Extension. The "new Function()" is not allowed because of Content Security Policy (https://developer.chrome.com/extensions/contentSecurityPolicy). I don't the use of this and "eval" are good practice or not, can we find another way to replace this?

**Comment by foo123** [comment]
Hi, yes there is a way to do this without the new Function dynamic evaluation

All you have to do is pre-compile the templates as js classes code and then just require these templates in your application.

Else you must bypass or overide the Content Security POlicy on chrome

The new Function (which is another version slightly more secure than eval) is for dynamic in-memory compiled templates. So if you pre-compo\ile your templates it should work just fine. Just add a template cache folder. You should pre-compile the templates in node.

Hmm, now that i think about it, it wont work as expected since in the browser the node pre-compiled templates are not used.

Anyway, if this option works for you, we can make a slight update to Contemplate to take this into account

**Comment by foo123** [comment]
Or you can manualy include the precompiled templates in you aplication like this:

either with node-require

``` javascript
/* Contemplate assumed already included */
 var tplclass = require( 'path/to/cachedTplFile.js' )( Contemplate ), 
 tpl = new tplclass( id );

console.log(tpl.render(data));
```

or just use a script tag:

``` html
<script src="path/to/cachedTplFile.js"></script>
```

``` javascript
var tplclass = Contemplate_tplname_Cached( Contemplate ),
 tpl = new tplclass( id );

console.log(tpl.render(data));
```

you **can even use requireJS to load the cached template as it is a UMD module**

**Comment by foo123** [comment]
Note that i already use Contemplate in a [firefox extensino](https://github.com/foo123/mark-I) and havent found a way to add the Contemplate engine in the core extension yet (which runs under different conditions and conventions), but i use the engine in a page generated by the extension which works as a normal web page

**Comment by foo123** [comment]
To pre-compile the templates in node just do this in a node script

``` javascript

// load Contemplate engine
var Contemplate = require('path/to/Contemplate.js');

// make sure the cache folder already exists
Contemplate.setCacheDir('path/to/cahe folder');
// dynamically update the cached template if original template has changed
Contemplate.setCacheMode(Contemplate.CACHE_TO_DISK_AUTOUPDATE);

// define the templates you want to precompile
Contemplate.add({

'tpl1': 'path/to/tpl1',
'tpl2': 'path/to/tpl2'
// ..
});

// pre-compile them
Contemplate.tpl('tpl1');
Contemplate.tpl('tpl2');
// ..

// get the per-compiled templates from the cahe folder
```

Then run the script and all the referenced templates will be compiled in the cache folder
